### ISSUE TITLE
We should always recreate the configured streams

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mavlink/mavlink-camera-manager#206]
We should always recreate the configured streams if this wasn't the user's intent to remove them. 

And because Linux could change the device path, especially in a bad-contact situation, we should never trust the old device path when recreating the stream.

**Comment by patrickelectric** [comment]
> We should always recreate the configured streams if this wasn't the user's intent to remove them.
> 
> And because Linux could change the device path, especially in a bad-contact situation, we should never trust the old device path when recreating the stream.

But that's what we are currently doing with USB devices, no ?
