### ISSUE TITLE
Support for raspberry pi camera

### ISSUE THREAD

**Issue by londi** [mavlink/mavlink-camera-manager#268]
Hi
I'm not sure if it's a bug or if the raspberry pi connected via csi is not compatible.
I use a raspberry pi 4 with 8GB Ram and raspbian 32bit.

I do not see any settings about fps and be not able to start a stream.
<img width="133" alt="pi-camera" src="https://github.com/mavlink/mavlink-camera-manager/assets/7037092/6b818688-bb82-4a58-85cf-03b5db384617">

(the camera is working)

**Comment by londi** [comment]
update: same issue with raspberry pi and an ordinary usb camera

**Comment by patrickelectric** [comment]
it should work with usb cameras without problems, what kind of behaviour are you seeing ?

**Comment by londi** [comment]
I have started mavlink-camera-manager as follow:
`./mavlink-camera-manager-armv7 --mavlink=serial:/dev/ttyACM0:57600`

I can configure the stream of a usb camera:
<img width="1276" alt="usb" src="https://github.com/mavlink/mavlink-camera-manager/assets/7037092/a7d3e84b-a774-4cef-96ec-4993a731d9ec">

But I can not create a Session on the webrtc page:

<img width="418" alt="webrtc" src="https://github.com/mavlink/mavlink-camera-manager/assets/7037092/5e21f081-175b-4bc1-b2ff-1bf4e537b5dd">

And on Qgroundcontrol is no image visible. 

The usb camera led is on as soon as I start the stream (configure stream button).

Have you an idea what the problem could be? :)

**Comment by joaoantoniocardoso** [comment]
Hi @londi, can you try to enable camera legacy mode? You can do it by running the following on a terminal inside your Raspberry Pi:

```bash
sudo raspi-config nonint do_legacy 0
```

(note: `0` is to **enable**, `1` to **disable** the legacy mode)

Then try to locate a new device `mmal`:

![image](https://github.com/mavlink/mavlink-camera-manager/assets/5920286/ce7af1c9-8ee9-4779-9837-8a57afac95d4)

Hope it helps, thanks

**Comment by joaoantoniocardoso** [comment]
I'm closing it for now, feel free to comment or create other issues as you wish.
