### ISSUE TITLE
MCM fails to answer requests on the signalling channel

### ISSUE THREAD

**Issue by rafaellehmkuhl** [mavlink/mavlink-camera-manager#295]
I'm attaching two logs to help debugging the problem.

I was using Cockpit fine with the BlueOS MCM, and when I restarted Cockpit, the stream didn't connect.
I took a look at the logs from cockpit and it was sending the signals requesting the streams correctly, but MCM was not responding to them, neither logging the requests. So I just restarted MCM and everything worked.

The first (oldest) log is when the problem happened, and the more recent one was after the restart.

[bug-mcm-no-webrtc-comms.zip](https://github.com/mavlink/mavlink-camera-manager/files/13297711/bug-mcm-no-webrtc-comms.zip)

**Comment by joaoantoniocardoso** [comment]
Not reproducible, possibly closed by #384
