### ISSUE TITLE
MCM doesn't stop sending data when webrtc connection is closed.

### ISSUE THREAD

**Issue by maphstr** [mavlink/mavlink-camera-manager#328]
This is blueOs v1.1.1. Stream is 1920x1080 rtsp. 

We were watching the network tab on task-manager in windows. Opening cockpit and closing the tab the received data increases by ~10mb/s every time. Closing cockpit does not 'stop' the incoming data. After 4-5 repeats all the bandwidth from the ROV was used up.

**Comment by joaoantoniocardoso** [comment]
Hi @maphstr, thanks for the report, that's due to a thread leak, we are currently working on that! :)

**Comment by joaoantoniocardoso** [comment]
Duplicate of https://github.com/mavlink/mavlink-camera-manager/issues/250
