### ISSUE TITLE
RTSP streams failing for JPEG and YUYV

### ISSUE THREAD

**Issue by joaoantoniocardoso** [mavlink/mavlink-camera-manager#363]
From our manual testing of the current master (2b1dc02dd4152af3597550f916b89cf24871e1cb):

> RTSP streams for JPEG/YUYV are behaving inconsistently both for v4l and testsrc, and sometimes die immediately or after a couple of seconds, entering some locked state

**Comment by lingaspeakingspider** [comment]
Facing the same problem here. What video streaming method works for now?

**Comment by joaoantoniocardoso** [comment]
> Facing the same problem here. What video streaming method works for now?

- RTSP, UDP (plus WebRTC) for H264
- UDP for JPEG
- UDP for YUYV, as long as the receiver uses the SDP file

**Comment by lingaspeakingspider** [comment]
Can QGC display UDP+JPEG?

**Comment by lingaspeakingspider** [comment]
Nope, QGC doesn't show any video output. Only the record button

**Comment by joaoantoniocardoso** [comment]
UDP+JPEG seems to be only working when receiving with MPV or VLC when using the SDP file.

**Comment by joaoantoniocardoso** [comment]
Fixed by #426 and #427.
