### ISSUE TITLE
README: Document which streams are provided automatically via webrtc

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/mavlink-camera-manager#367]
At the moment the readme is not clear when a webrtc stream is provided automatically by a source.
E.g: A RTSP redirect will also be provided as a webrtc.

**Comment by joaoantoniocardoso** [comment]
maybe in the key-features section, change it as in:
```diff
--- WebRTC-ready, for modern control stations
+++ WebRTC-ready, for modern control stations, available from any H264 source.
```

what do you think?

**Comment by patrickelectric** [comment]
Perfect!
